import pandas as pd

from common.datetime_config import DateTimeConfig
from common.session import Session


class PostCodesInfo(DateTimeConfig, Session):
    def __init__(self):
        DateTimeConfig.__init__(self)
        Session.__init__(self)

    def post_code_loop(self):
        post_codes = [
            'WA8 7BN',
            'SK7 1EY',
            'CF47 8HX',
            'SA17 5DQ',
            'WN5 8RY',
            'SK5 6SX',
            'HD6 4BH',
            'NR25 7YD',
            'OX18 3JT',
            'CA28 6JE',
            'B68 8HW',
            'N1 2XH',
            'SW16 1JA',
            'HR9 7FQ',
            'E14 3LR',
            'S74 9DJ',
            'CF39 9SG',
            'NE25 9RD',
            'SP7 9NX',
            'B9 5ET',
            'NG6 9HT',
            'BN1 5DP',
            'EH11 1PQ',
            'KY7 6RH',
            'BS24 8GB',
            'SM1 2LL',
            'PO7 5HQ',
            'LU3 3TJ',
            'IG11 8SU',
            'S10 1UY',
            'B11 4JG',
            'CM9 6ZR',
            'AB12 4BH',
            'PO38 1EP',
            'SK4 2LL',
            'CR5 1NY',
            'BN2 5EG',
            'BS14 0AH',
            'WS13 6AT',
            'YO12 5NP',
            'OX18 1DB',
            'SG13 8HY',
            'RM2 6LD',
            'ML3 6DR',
            'SA13 1SW',
            'GU10 3LS',
            'SS8 0HN',
            'WS3 3DL',
            'PE7 8PL',
            'CF81 8NZ',
            'NG12 4AW',
            'MK44 1NA',
            'LL12 7LU',
            'AB22 8DL',
            'DN4 6SB',
            'SE14 5TB',
            'SP10 3DH',
            'NP23 6AW',
            'WS2 8TS',
            'LS22 6AG',
            'SK14 1QW',
            'OX4 3AP',
            'CV1 2BH',
            'ST8 6QQ',
            'SS8 9FD',
            'SR8 3LN',
            'EH9 2PH',
            'ME5 9BS',
            'BA3 2EY',
            'EH49 6AA',
            'DY8 5QZ',
            'SO45 2HF',
            'LE2 6FP',
            'WA15 9PU',
            'ME11 5AP',
            'RG6 5TG',
            'TS23 2EP',
            'SW19 5AE',
            'PL3 5NQ',
            'M6 8WN',
            'NR30 4HQ',
            'LE15 7JQ',
            'EH21 7LR',
            'NN1 2SR',
            'E1 1RR',
            'DD8 3RQ',
            'SS7 1DQ',
            'SG4 9TE',
            'NE30 2LY',
            'DL3 9EW',
            'EX18 7LZ',
            'LE3 8DT',
            'B65 9BG',
            'PO14 2DX',
            'CO12 3HJ',
            'HA3 6NT',
            'PR1 9RP',
            'AB31 5ZN',
            'EH3 5PA',
            'KA13 7NJ',
            'SA14 8HY',
            'DG8 7DA',
            'RM14 3EA',
            'ME16 0FG',
            'FY6 7LY',
            'PR4 5AS',
            'KA13 6LQ',
            'PL9 7RD',
            'WV2 3DY',
            'WV10 0SR',
            'BB9 0SA',
            'NW3 7QJ',
            'PL21 0BN',
            'FK12 5BW',
            'CV9 3QY',
            'DY7 6DB',
            'IG8 0LQ',
            'PR2 1BE',
            'TN15 6XN',
            'NE30 2HJ',
            'SA2 0RA',
            'AB24 4NN',
            'LN11 0BW',
            'WV6 7NX',
            'EN7 6PT',
            'B73 6UG',
            'HR9 7EH',
            'CF5 3NB',
            'LS21 3JB',
            'SL9 9RA',
            'M9 8AA',
            'SW1X 8LS',
            'CT19 5TT',
            'PA5 0NW',
            'YO14 9BX',
            'NR30 2BN',
            'LS26 8QJ',
            'BH15 1NT',
            'PE2 5XH',
            'SA65 9QH',
            'IP2 9BJ',
            'DL13 4BQ',
            'DD2 1PP',
            'ML5 5RD',
            'NR6 5FR',
            'CH65 9AA',
            'WF11 8ES',
            'TF8 7PF',
            'PR9 9RA',
            'CH42 8PR',
            'LL59 5LY',
            'CO1 2SG',
            'NG16 3LN',
            'WS8 7AT',
            'SO40 4XU',
            'NN11 4TU',
            'B61 8RP',
            'ST16 1EF',
            'TQ3 1NX',
            'NW11 0DL',
            'SS9 2QR',
            'DE21 5DR',
            'M46 9RT',
            'TS18 2BQ',
            'PA14 5TB',
            'LE65 2YA',
            'NP11 3AQ',
            'UB7 9AD',
            'NE33 2EW',
            'WR5 3RB',
            'WF12 7AF',
            'LL18 4FE',
            'PR9 7SX',
            'M26 4HY',
            'GL20 8AY',
            'UB6 8EY',
            'LE67 3HJ',
            'KA18 4QA',
            'PA2 9LS',
            'EN1 2DQ',
            'SY23 1BB',
            'SA2 9BJ',
            'DE21 6EJ',
            'S3 9GW',
            'DY6 7ST',
            'YO10 3RP',
            'NW1 5QT',
            'LE4 4NQ',
            'SG2 0QR',
            'LD3 9DL',
            'CR0 4HD',
            'PO5 1RQ',
            'EH4 8DJ',
            'IP7 5PZ',
            'ST7 3JT',
            'CV3 5DJ',
            'DG13 0BH',
            'BH23 2PR',
            'M19 1FZ',
            'CM9 5JA',
            'SK23 6AB',
            'BN14 9RP',
            'TN23 7TE',
            'EX4 8PY',
            'S44 6PZ',
            'DN15 9FJ',
            'SN25 2QN',
            'BA21 3RE',
            'SW19 5ZF',
            'HU18 1BX',
            'SK17 9RY',
            'ME16 0WD',
            'EH54 6BN',
            'BD19 6EU',
            'CT11 7LN',
            'N19 5BL',
            'PO8 8SE',
            'LE9 3BF',
            'AB24 2EW',
            'SO40 8XS',
            'NE61 2RH',
            'ME10 3PH',
            'WD17 1QB',
            'L7 7AF',
            'CH5 1PF',
            'NW1 2ES',
            'BS10 6PD',
            'TF10 7AY',
            'WA8 3YB',
            'BH8 8AS',
            'ML10 6NN',
            'NR31 8RJ',
            'CH63 1JB',
            'DL7 8AY',
            'SE20 8FP',
            'NG21 9ES',
            'OL16 4EH',
            'GU24 9FT',
            'B38 9LZ',
            'TS7 0AE',
            'LE12 8NY',
            'HA6 2SZ',
            'NG4 1GB',
            'CM23 5SZ',
            'CH66 1LH',
            'YO13 0AQ',
            'TS16 0HB',
            'GU14 8HW',
            'WS5 4RP',
            'BA2 7WB',
            'B73 6PS',
            'NR3 4PR',
            'N4 2FR',
            'KT23 4LW',
            'WV13 2SG',
            'IV30 6AW',
            'BN1 9HW',
            'PE21 6NW',
            'CV4 9PE',
            'CO13 0JU',
            'B18 4EP',
            'E15 3DT',
            'BH16 6DX',
            'WN5 7BT',
            'WV9 5DL',
            'SW16 6BA',
            'SS1 3BG',
            'CO10 2PW',
            'PO6 2JB',
            'GL52 6NR',
            'N2 0BE',
            'PO4 8QA',
            'W1D 7PP',
            'SO43 7BE',
            'ME16 0EX',
            'RG31 4XN',
            'G65 9PD',
            'ML3 7QH',
            'BH25 5PP',
            'CB4 1HW',
            'DT5 1HJ',
            'IP13 0ST',
            'NP22 5PU',
            'CF62 6AZ',
            'S21 4GY',
            'NE31 1BZ',
            'BH19 2AG',
            'BS10 6AJ',
            'L7 0JG',
            'LS23 6DU',
            'CH41 1BG',
            'N17 0UT',
            'BS22 7QP',
            'BA1 3RU',
            'LA4 5PX',
            'RH19 1NA',
            'CR3 6GR',
            'BB2 2RD',
            'NW6 3LP',
            'SN1 3AE',
            'TA8 2HF',
            'M28 1HW',
            'BS36 2HX',
            'EX4 6SL',
            'W11 1AG',
            'CR7 7DY',
            'NR32 4HQ',
            'CA3 8XA',
            'TN4 8XR',
            'RG30 4DR',
            'SW18 5RD',
            'S32 3ZB',
            'SE20 8BB',
            'M33 2LN',
            'NP12 3NP',
            'EX14 1NX',
            'BS21 6HS',
            'ST7 2ND',
            'N9 7AX',
            'RG41 2TL',
            'S5 7LB',
            'NR32 4LU',
            'ST5 3DJ',
            'E6 2EP',
            'EH8 7HP',
            'PE13 4AB',
            'NN9 6TT',
            'SY22 5HL',
            'HP15 7BY',
            'LU2 7FL',
            'WS13 8PE',
            'B33 8TH',
            'GU11 3UF',
            'BL6 5AD',
            'LL14 2PE',
            'BB3 2PX',
            'SO16 3QE',
            'DN12 2JN',
            'HD8 0EE',
            'LE3 0LS',
            'EH7 6UW',
            'L23 0YE',
            'GU35 0GJ',
            'CH4 8DY',
            'WA3 2TX'
        ]

        self.post_code_data = [self.post_code_api(post_code) for post_code in post_codes]

    def post_code_api(self, post_code: str):
        print(post_code)
        url = f'https://findthatpostcode.uk/postcodes/{post_code}.json'
        response = self.s.get(url)
        data = response.json()

        attributes = data['data']['attributes']

        info = {
            'post_code': post_code,
            'latitude': attributes['lat'],
            'longitude': attributes['long'],
            **self.parse_attributes(attributes)
        }

        return info

    def parse_attributes(self, attributes):
        for key in ['ru11ind', 'ruc21', 'location', 'oac11', 'lat', 'long']:
            if key in attributes.keys():
                attributes.pop(key)

        return attributes

    def to_dataframe(self):
        df = pd.DataFrame(self.post_code_data)
        # df.to_excel('post_code_lat_long.xlsx', index=False, engine='openpyxl')
        df.to_csv('post_code_lat_long.csv', index=False)
        df.to_parquet('post_code_lat_long.parquet', index=False, engine='pyarrow')

    def main(self):
        self.post_code_loop()
        self.to_dataframe()


if __name__ == '__main__':
    PostCodesInfo().main()
